# Generated by Django 6.0 on 2025-12-31 00:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('product_stage', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=4)),
                ('time_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('sample_type', models.CharField(choices=[('I', 'InProcess'), ('S', 'Stability'), ('F', 'FinishedProduct')], max_length=1)),
                ('storage_conditions', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(blank=True, max_length=64, null=True)),
                ('room_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_name', models.CharField(max_length=16)),
                ('version_number', models.DecimalField(decimal_places=1, max_digits=3)),
                ('effective_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_username', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('department', models.CharField(max_length=255)),
                ('training_completed', models.BooleanField(default=False)),
                ('is_analyst', models.BooleanField(default=False)),
                ('is_administrator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lims_app.sample')),
                ('product_lot_number', models.DecimalField(decimal_places=0, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='InProcess',
            fields=[
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lims_app.sample')),
                ('time_sampled', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stability',
            fields=[
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lims_app.sample')),
                ('stability_conditions', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.location'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=64)),
                ('min_use_range', models.DecimalField(decimal_places=6, max_digits=16)),
                ('max_use_range', models.DecimalField(decimal_places=6, max_digits=16)),
                ('in_use', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.location')),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.sop')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='sop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.sop'),
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_name', models.CharField(max_length=255)),
                ('cas_number', models.CharField(max_length=12)),
                ('lot_number', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('manufacturing_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.sop')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_description', models.TextField()),
                ('service_interval', models.CharField(max_length=64)),
                ('next_service_date', models.DateField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.equipment')),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.sop')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_acceptable_result', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('max_acceptable_result', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.sop', unique=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='SampleTestLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing_analyst', models.CharField(max_length=64)),
                ('reviewing_analyst', models.CharField(max_length=64)),
                ('test_result', models.DecimalField(decimal_places=6, max_digits=16)),
                ('deadline', models.DateTimeField()),
                ('pass_or_fail', models.BooleanField(default=False)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.sample')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestEquipmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.equipment')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestReagentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_used', models.DecimalField(decimal_places=6, max_digits=16)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.reagent')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.test')),
            ],
        ),
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.PositiveSmallIntegerField()),
                ('analyst_supervisor', models.CharField(max_length=64)),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_profile', to='lims_app.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_supervisor', models.BooleanField(default=False)),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='lims_app.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserReagentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_manager', models.CharField(max_length=64)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.reagent')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserSampleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_analyst', models.CharField(max_length=64)),
                ('aliquoting_analyst', models.CharField(blank=True, max_length=64, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.sample')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserSOPAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa_author', models.CharField(max_length=64)),
                ('qa_reviewer', models.CharField(max_length=64)),
                ('qa_approver', models.CharField(max_length=64)),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.sop')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='VersionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_version_number', models.DecimalField(decimal_places=1, max_digits=3)),
                ('new_version_number', models.DecimalField(decimal_places=1, max_digits=3)),
                ('old_effective_date', models.DateField()),
                ('new_effective_date', models.DateField()),
                ('change_date', models.DateField()),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.sop')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_technician', models.CharField(max_length=64)),
                ('warehouse_facility', models.CharField(max_length=64)),
                ('warehouse_company', models.CharField(max_length=64)),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.sop')),
            ],
            options={
                'unique_together': {('warehouse_facility', 'warehouse_company')},
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.warehouse'),
        ),
        migrations.CreateModel(
            name='WarehouseClientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_shipped', models.DecimalField(decimal_places=0, max_digits=4)),
                ('delivery_service', models.CharField(max_length=64)),
                ('shipping_time', models.DateTimeField()),
                ('delivery_time', models.DateTimeField()),
                ('acceptable_delivery', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.client')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.warehouse')),
            ],
        ),
    ]
